services:
  server:
    build: /
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - "SPRING_PROFILES_ACTIVE=container"
  db:
    image: mysql:9.1.0
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 30s
      retries: 10

volumes:
  db-data: